name: Node.js CI

on:
  push:
    branches: [main, typescript-migration]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 # Updated to v4 for better performance

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4 # Updated to v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./server/package-lock.json" # Caches your npm downloads

      - name: Install dependencies
        run: npm install
        working-directory: ./server

      - name: Run tests
        run: npm test
        working-directory: ./server
        env:
          # IMPORTANT: Telling GitHub to use ESM VM modules
          NODE_OPTIONS: "--experimental-vm-modules"
          # Your Secrets
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          JWT_SECRETE_KEY: ${{ secrets.JWT_SECRETE_KEY }}
          # Dummy URL for the Memory Server (if needed by your DB config)
          MONGO_URI: "mongodb://localhost:27017/test"
